### ISSUE TITLE
Data being broken into multiple parts when sending

### ISSUE THREAD

**Issue by dkraide** [jchristn/SuperSimpleTcp#141]
Hi! I have a strange problem.
In my tests, the first and second try work fine. But the third time I send a json string, my server receives this string in 2 or more different parts. The Events_DataReceived method is called 2 or more times with parts of the text that was sent. This only happens after the third attempt. The first and second always work.

![image](https://user-images.githubusercontent.com/43674712/171202075-15f3f2a6-846f-40c0-9f63-d7a28ca0beb6.png)
![image](https://user-images.githubusercontent.com/43674712/171202241-ee73a37f-153d-4235-b02b-07378d0ab0ac.png)
![image](https://user-images.githubusercontent.com/43674712/171202631-b21ffbe1-ef37-427a-8747-863ef005844e.png)

I got this error only in other machine in the network. In localhost this not happen

**Comment by jchristn** [comment]
Hi @dkraide this isn't an error, it's by design.  SuperSimpleTcp doesn't implement framing, i.e. if you send data, it may be received as multiple fragments on the other end.  The only ways to get around this are to either A) use a library with framing (which ensure exactly what is sent is what is received by the other side) or B) add your own framing layer.  Please check out [WatsonTcp](https://github.com/jchristn/watsontcp) for a nearly identical implementation of this library but with framing.
